import{CommonModule} from '@angular/common';
import {MatButtonModule,MatIconModule,MatCheckboxModule,
  MatRadioModule,
  MatCardModule,
  MatDatepickerModule,
  MatFormFieldModule,
  MatNativeDateModule,
  MatFormFieldControl,
  MatInputModule,
  MatOptionModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatTooltipModule,
  MatDividerModule,
  MatListModule,
  MatExpansionModule,
  MatGridListModule,
  MatStepperModule,
  MatTabsModule,
  MatTreeModule,
  
} from '@angular/material';
import{NgModule} from '@angular/core';
@NgModule({
    imports: [MatButtonModule,MatIconModule,MatCheckboxModule,
      MatRadioModule,
      MatCardModule,
      MatDatepickerModule,
      MatFormFieldModule,
      MatNativeDateModule,
      MatInputModule,
      MatOptionModule,
      MatSelectModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
  MatTooltipModule,
  MatDividerModule,
  MatListModule,
  MatExpansionModule,
  MatGridListModule,
  MatStepperModule,
  MatTabsModule,
  MatTreeModule,
    ],
    exports: [MatButtonModule,MatIconModule,MatCheckboxModule,
      MatRadioModule,
      MatCardModule,
      MatDatepickerModule,
      MatFormFieldModule,
      MatNativeDateModule,
      MatInputModule,
      MatOptionModule,
      MatSelectModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
  MatTooltipModule,
  MatDividerModule,
  MatListModule,
  MatExpansionModule,
  MatGridListModule,
  MatStepperModule,
  MatTabsModule,
  MatTreeModule,
    ],
  })
  export class MaterialModule { }

